<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SeniorDeveloperTest.Application\SeniorDeveloperTest.Application.csproj" />
    <ProjectReference Include="..\SeniorDeveloperTest.Domain\SeniorDeveloperTest.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
